# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Euclidean distance between two points.
NULL

euclid <- function(a, b) {
    .Call('_ggrepel_euclid', PACKAGE = 'ggrepel', a, b)
}

centroid <- function(b, hjust, vjust) {
    .Call('_ggrepel_centroid', PACKAGE = 'ggrepel', b, hjust, vjust)
}

intersect_circle_rectangle <- function(c, r) {
    .Call('_ggrepel_intersect_circle_rectangle', PACKAGE = 'ggrepel', c, r)
}

intersect_line_circle <- function(p1, p2, r) {
    .Call('_ggrepel_intersect_line_circle', PACKAGE = 'ggrepel', p1, p2, r)
}

intersect_line_rectangle <- function(p1, p2, b) {
    .Call('_ggrepel_intersect_line_rectangle', PACKAGE = 'ggrepel', p1, p2, b)
}

select_line_connection <- function(p1, b, side = 0L) {
    .Call('_ggrepel_select_line_connection', PACKAGE = 'ggrepel', p1, b, side)
}

approximately_equal <- function(x1, x2) {
    .Call('_ggrepel_approximately_equal', PACKAGE = 'ggrepel', x1, x2)
}

repel_boxes2 <- function(data_points, point_size, point_padding_x, point_padding_y, boxes, xlim, ylim, hjust, vjust, force_push = 1e-7, force_pull = 1e-7, max_time = 0.1, max_overlaps = 10, max_iter = 2000L, direction = "both", verbose = 0L) {
    .Call('_ggrepel_repel_boxes2', PACKAGE = 'ggrepel', data_points, point_size, point_padding_x, point_padding_y, boxes, xlim, ylim, hjust, vjust, force_push, force_pull, max_time, max_overlaps, max_iter, direction, verbose)
}

